project:
  type: website
  output-dir: docs
    
website:
  title: "George James"
  image: "Picture.jpg" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "Project 1"
      - href: project2.qmd
        text: "Project 2"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


